### PR TITLE
Config changes to comply with MISP version 2.4.79 

### PR DESCRIPTION
**Pull request by ppanero**
Config changes to comply with MISP version 2.4.78 adn 2.4.79 changes

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @ppanero @traylenator is this ready to be merged?

**Comment by ppanero** [comment]
@bastelfreak it is from our side. I just assigned to someone else in order not to merge my own code. Cheers and thanks

**Comment by bastelfreak** [comment]
I'm happy to merge this if you want. I just wasn't sure if you need specific feedback from @traylenator because he is assigned.

**Comment by ppanero** [comment]
@bastelfreak no need of special feedback. In our side I am the one maintaining the module. Just wanted another pair of eyes. 

Please merge :)

**Comment by traylenator** [comment]
+1

**Pull request merged**
